site_name: benny
site_url: https://www.playbenny.com/
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: amber
  logo: assets/benny_logo_400T.png
  favicon: assets/favicon-32x32.png
  features: 
    - navigation.footer
    - header.autohide
    - navigation.expand
    - content.code.copy
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  generator: false
repo_url: https://github.com/playbenny/benny    
nav:
  - About: index.md
  - Installation: installation.md
  - How to use benny:
    - Launcher : launcher.md
    - Blocks : blocks.md
    - Sidebar : sidebar.md
    - Connections : connections.md
    - States : states.md
    - Waves : waves.md
    - Panels : panels.md
    - Recall : recall.md
    - Top bar : topbar.md
    - Midi Control: controllers.md
    - Mixer : mixer.md
    - Recording: recording.md
  - List of blocks : blockipedia.md 
  - Keyboard shortcuts: keyboard_shortcuts.md
  - Playing live sets with benny: live_sets.md
  - Developing blocks: developing.md
  - Contribute: contribute.md